### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by zeinalii** [data301-2020-winter2/course-project-solo_109#1]
removed

**Comment by ZuShi0** [comment]
@zeinalii Hello, the comments for this issue have no relation to my dataset or milestone. My dataset has GPU (graphics card) specs, and has no relation to Medical Insurance at all. I'm assuming this issue wasn't meant for my project

**Comment by zeinalii** [comment]
Sorry. Probably I messed up and opened someone else's project. Here are the comments:

## High priority (must-fix)
- [ ] Printing the dataset alone does not explain the data. You need to add a section called dataset and explain the data. What are the columns and what do they show? 
- [ ] The EDA task (Task 4) is different from the Analysis task (Task 5). You need to add a section for EDA. Right now you only did task 5 and not task 4. The EDA is “exploratory” in nature and is done at a superficial level to get counts of columns, limits, ranges, understand the data distribution, and a cursory look at the relationships between the columns. Think of it as a ‘quick and dirty’ analysis of your data in preparation for a more thorough. Move those analyses to task 5 and add EDA.


## Low priority (fix if there is time)

- [ ] Make your report look better by using markdown tools such as the followings: 
                    Multi-level Headers (``, ##, ###, #### etc…)
                    Bold text (surround with **bold text**)
                    Italic text (surround with *italic text*)
                    Unordered lists (- text or * text, + text)
                    Ordered lists (1. text)
                    Images (![path_to_image.png])
                    Code (surround code in markdown cells with single line or multi-line code)
                    Quoted text (start line with > text)
                    Links ([text placeholder](https:/cbc.ca))
                    Math symbols using $\latex(surroundwith‘‘like:‘$\lambda`)
                    Horizontal Line (three dashes: ---)

**Comment by ZuShi0** [comment]
High Prio issues have been taken care of. Closing the issue
